namespace:
  name: sandbox
service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP
image:
  repository: lksa/techtrends 
  tag: latest
  pullPolicy: IfNotPresent

resources: 
  requests: 
    memory: 64Mi
    CPU: 250m
  limits:
    memory: 128Mi
    CPU: 500m

replicaCount: 1

containerPort: 3111
livenessProbe:
    path: /healthz
    port: 3111
readinessProbe:
    path: /healthz
    port: 3111
